<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-04-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VeterinarioCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=3)),
                ('telefone', models.CharField(max_length=15)),
                ('crmv', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
    ]
=======
# Generated by Django 5.0.4 on 2024-04-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VeterinarioCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=3)),
                ('telefone', models.CharField(max_length=15)),
                ('crmv', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
    ]
>>>>>>> a8df29caf251d889a965943da2441df3d7db4e23
