# Generated by Django 5.0.4 on 2024-04-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutoresCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nometutor', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('logradouro', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=3)),
                ('telefone', models.CharField(max_length=15)),
                ('telefone2', models.CharField(max_length=15)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
    ]
