# Generated by Django 5.0.4 on 2024-04-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0002_tutorescadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nometutor', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('logradouro', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=255)),
                ('numero', models.IntegerField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='tutorescadastro',
            old_name='cpf',
            new_name='cep',
        ),
        migrations.RemoveField(
            model_name='tutorescadastro',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='tutorescadastro',
            name='telefone2',
        ),
    ]
