# Generated by Django 5.0.4 on 2024-04-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0003_tutor_rename_cpf_tutorescadastro_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinariocadastro',
            name='cidade',
            field=models.CharField(default='cidade', max_length=100, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='cidade',
            field=models.CharField(default='cidade', max_length=100, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='tutorescadastro',
            name='cidade',
            field=models.CharField(default='cidade', max_length=100, verbose_name='cidade'),
        ),
    ]
