# Generated by Django 5.0.4 on 2024-04-25 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0004_veterinariocadastro_cidade_alter_tutor_cidade_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TutoresCadastro',
            new_name='cadastroTutorModel',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
