# Generated by Django 5.0.4 on 2024-04-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0005_rename_tutorescadastro_cadastrotutormodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrotutormodel',
            name='password',
            field=models.CharField(default='passord', max_length=20, verbose_name='password'),
        ),
    ]
