# Generated by Django 5.0.4 on 2024-04-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0006_cadastrotutormodel_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeterinarioCadastroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('logradouro', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('cidade', models.CharField(default='cidade', max_length=100, verbose_name='cidade')),
                ('estado', models.CharField(max_length=3)),
                ('telefone', models.CharField(max_length=15)),
                ('crmv', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='VeterinarioCadastro',
        ),
    ]
