# Generated by Django 5.0.4 on 2024-04-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0007_veterinariocadastromodel_delete_veterinariocadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrotutormodel',
            name='cpf',
            field=models.CharField(default='cpf', max_length=11, verbose_name='cpf'),
        ),
    ]
