# Generated by Django 5.0.4 on 2024-04-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0008_cadastrotutormodel_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='cadastroAnimalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomepet', models.CharField(max_length=200)),
                ('especie', models.CharField(max_length=200)),
                ('porte', models.CharField(max_length=200)),
                ('raca', models.CharField(max_length=200)),
                ('cor', models.CharField(max_length=200)),
                ('sexo', models.CharField(max_length=200)),
                ('datanascimento', models.DateField(max_length=200)),
                ('cpftutor', models.CharField(max_length=200)),
            ],
        ),
    ]
