# Generated by Django 5.0.4 on 2024-05-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0009_cadastroanimalmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='agendamentoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banhoetosa', models.CharField(max_length=5)),
                ('tosahigienica', models.CharField(max_length=5)),
                ('vanicacao', models.CharField(max_length=5)),
                ('exameslaboratoriais', models.CharField(max_length=5)),
                ('microchipagem', models.CharField(max_length=5)),
                ('consultaclinica', models.CharField(max_length=5)),
                ('atendimentodomiciliar', models.CharField(max_length=5)),
                ('atendimento24horas', models.CharField(max_length=5)),
                ('hospedagem', models.CharField(max_length=5)),
                ('transporte', models.CharField(max_length=5)),
                ('adestramento', models.CharField(max_length=5)),
            ],
        ),
    ]
