# Generated by Django 5.0.4 on 2024-05-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0011_alter_agendamentomodel_adestramento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentomodel',
            name='adestramento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agendamentomodel',
            name='atendimento24horas',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agendamentomodel',
            name='atendimentodomiciliar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agendamentomodel',
            name='banhoetosa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agendamentomodel',
            name='consultaclinica',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agendamentomodel',
            name='exameslaboratoriais',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agendamentomodel',
            name='hospedagem',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agendamentomodel',
            name='microchipagem',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agendamentomodel',
            name='tosahigienica',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agendamentomodel',
            name='transporte',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agendamentomodel',
            name='vanicacao',
            field=models.BooleanField(default=False),
        ),
    ]
