# Generated by Django 5.0.4 on 2024-05-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0013_agendamentomodel_animal_agendamentomodel_tutor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamentomodel',
            old_name='vanicacao',
            new_name='vacinacao',
        ),
    ]
