# Generated by Django 5.0.4 on 2024-06-03 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0014_rename_vanicacao_agendamentomodel_vacinacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Serviço Temporário', max_length=200, unique=True)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='agendamentomodel',
            name='adestramento',
        ),
        migrations.RemoveField(
            model_name='agendamentomodel',
            name='atendimento24horas',
        ),
        migrations.RemoveField(
            model_name='agendamentomodel',
            name='atendimentodomiciliar',
        ),
        migrations.RemoveField(
            model_name='agendamentomodel',
            name='banhoetosa',
        ),
        migrations.RemoveField(
            model_name='agendamentomodel',
            name='consultaclinica',
        ),
        migrations.RemoveField(
            model_name='agendamentomodel',
            name='exameslaboratoriais',
        ),
        migrations.RemoveField(
            model_name='agendamentomodel',
            name='hospedagem',
        ),
        migrations.RemoveField(
            model_name='agendamentomodel',
            name='microchipagem',
        ),
        migrations.RemoveField(
            model_name='agendamentomodel',
            name='tosahigienica',
        ),
        migrations.RemoveField(
            model_name='agendamentomodel',
            name='transporte',
        ),
        migrations.RemoveField(
            model_name='agendamentomodel',
            name='vacinacao',
        ),
        migrations.AddField(
            model_name='agendamentomodel',
            name='data',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='agendamentomodel',
            name='horario',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AddField(
            model_name='agendamentomodel',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado'), ('cancelado', 'Cancelado')], default='aberto', max_length=10),
        ),
        migrations.AddField(
            model_name='agendamentomodel',
            name='servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.servicomodel'),
        ),
    ]
