# Generated by Django 5.0.4 on 2024-06-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0015_servicomodel_remove_agendamentomodel_adestramento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cadastroVacinaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacina', models.CharField(max_length=200)),
                ('datavacinado', models.DateField(max_length=200)),
                ('nomeveterinario', models.CharField(max_length=200)),
                ('proximavacina', models.DateField(max_length=200)),
                ('datavernifugo', models.DateField(max_length=200)),
                ('produtovernifugo', models.CharField(max_length=200)),
                ('dose', models.CharField(max_length=15)),
                ('pesoanimal', models.CharField(max_length=15)),
            ],
        ),
    ]
