# Generated by Django 5.0.4 on 2024-06-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0016_cadastrovacinamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinariocadastromodel',
            name='cep',
            field=models.CharField(default='000000000', max_length=255),
        ),
    ]
