# Generated by Django 5.0.4 on 2024-06-13 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0017_veterinariocadastromodel_cep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicomodel',
            name='preco',
        ),
    ]
